[package]
name = "imgui-rs-vulkan-renderer"
description = "A Vulkan renderer for imgui-rs using Ash."
readme = "README.md"
keywords = ["imgui", "vulkan", "ash"]
homepage = "https://github.com/adrien-ben/imgui-rs-vulkan-renderer"
repository = "https://github.com/adrien-ben/imgui-rs-vulkan-renderer"
documentation = "https://docs.rs/imgui-rs-vulkan-renderer"
license = "MIT"
version = "0.4.1"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"

exclude = [
    "assets/*",
    "compile_shaders.*"
]

[dependencies]
log = "0.4"
imgui = "^0.4"
ash = ">=0.29"
ultraviolet = "0.4"

[dev-dependencies]
simple_logger = "1.6"
winit = "0.22"
imgui-winit-support = "^0.4"
raw-window-handle = "0.3"
ash = "0.31"
image = "0.23"
